@extends ('layouts.masterLayout')

@section ('pagetitle')
	Epimed - Batch History Form
@stop

@section ('content')
		 	
	<div class="bg-grey-warm text-primary">		
		<div id="form_title" class="text-center">
			<h4>FINAL PRODUCT BATCH HISTORY RECORD</h4>
		</div>		
	
		<div id="form_subtitle" class="text-center">
			<h6>IHR-013</h4>
		</div>		
	</div>
	<hr>
	<div>	
		{{ Form::open (array ('route' => 'store_batch_history', 'method' => 'post', 'class' => 'form-horizontal', 'role' => 'form')) }}	
			<div class="form-group">
				{{ Form::label('final_product', 'Final Product', 	array('class' => 'col-sm-2 control-label form-inline text-primary')) }}
				<div class="col-sm-4">
					{{ Form::text('final_product', 	$product->name,				array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('final_lot_#', 'Final Lot #:', 		array('class' => 'col-sm-2 control-label col-sm-offset-1 form-inline text-primary')) }}
				<div class="col-sm-2">
					{{ Form::text('final_lot_#', 	$batch->lot,				array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>				
			</div>
			
			<div class="form-group">
				{{ Form::label('catalog_#', 'Catalog #', 			array('class' => 'col-sm-2 control-label form-inline text-primary')) }}
				<div class="col-sm-4">
					{{ Form::text('catalog_#', 	$product->alphanumeric,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('final_quantity', 'Final Quantity',	array('class' => 'col-sm-2 control-label col-sm-offset-1 form-inline text-primary')) }}
				<div class="col-sm-2">
					{{ Form::text('final_quantity', 	@$batch->sterilization->quantity ,			array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
			{{-- "Todo add button to show BoM here" --}}
			<div class="form-group">
				{{ Form::label('component_product_#0', 'Componenet Product #',	array('class' => 'col-sm-3 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-3">
					{{ Form::text('component_product_#0', 	'',					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('lot_#0', 'Lot #:',								array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2 col-sm-offset-1">
					{{ Form::text('lot_#0', 	'',								array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
			
			<div class="form-group">
				{{ Form::label('component_product_#1', 'Componenet Product #',	array('class' => 'col-sm-3 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-3">
					{{ Form::text('component_product_#1', 	'',					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('lot_#1', 'Lot #:',								array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2 col-sm-offset-1">
					{{ Form::text('lot_#1', 	'',								array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
			
			<hr>
						
			<div id="pouch_label" class="text-primary text-center">
				<h4>Pouch Label</h4>
			</div>
			<?php $batchGenerations = @$batch->batchPouchLabel->batchGenerations or $batchGenerations = array();?>
			@foreach($batchGenerations as $generation )
				<div class="form-group">
					{{ Form::label('pouch_generated_by'.$generation->id, 	'Generated By:',						array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-4">
						{{ Form::text('pouch_generated_by'.$generation->id, $generation->generator->user->username,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('pouch_generated_date'.$generation->id, 	'Date:',								array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-2">
						{{ Form::text('pouch_generated_date'.$generation->id,$generation->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('pouch_generated_#'.$generation->id, 	'Generated#:',							array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-1">
						{{ Form::text('pouch_generated_#'.$generation->id, 	$generation->amount,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
				</div>
			
				<div class="form-group">
					{{ Form::label('pouch_approved'.$generation->id, 			'Approved For Use By:',							array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-4">
						{{ Form::text('pouch_approved_by'.$generation->id, 		@$generation->approval->approver->user->username,array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('pouch_approved_date'.$generation->id, 		'Date:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-2">
						{{ Form::text('pouch_approved_date'.$generation->id, 	@$generation->approval->date,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('pouch_approved_#'.$generation->id, 			'Used#:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-1">
						{{ Form::text('pouch_approved_#'.$generation->id, 		@$generation->used,								array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
				</div>
			@endforeach

			<div class="form-group">
				{{ Form::label('pouch_destroyed_by', 	'Undestroyed Labels Destroyed By:',				array('class' => 'col-sm-3 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-3">
					{{ Form::text('pouch_destroyed_by', @$batch->batchPouchLabel->batchDestruction->destroyer->user->username,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('pouch_destroyed_date', 	'Date:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('pouch_destroyed_date', @$batch->batchPouchLabel->batchDestruction->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('pouch_destroyed_#', 	'Destroyed#:',									array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-1">
					{{ Form::text('pouch_destroyed_#', 	@$batch->batchPouchLabel->batchDestruction->amount,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
						
			<hr>
			
			<div id="carton_label" class="text-primary text-center">
				<h4>Carton Label</h4>
			</div>
			<?php $batchGenerations = @$batch->batchCartonLabel->batchGenerations or $batchGenerations = array();?>
			@foreach($batchGenerations as $generation )
				<div class="form-group">
					{{ Form::label('carton_generated_by'.$generation->id, 		'Generated By:',						array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-4">
						{{ Form::text('carton_generated_by'.$generation->id, 	$generation->generator->user->username,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('carton_generated_date'.$generation->id, 	'Date:',								array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-2">
						{{ Form::text('carton_generated_date'.$generation->id, 	$generation->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('carton_generated_#'.$generation->id, 		'Generated#:',							array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-1">
						{{ Form::text('carton_generated_#'.$generation->id, 	$generation->amount,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
				</div>

				<div class="form-group">
					{{ Form::label('carton_approved_by'.$generation->id, 	'Approved For Use By:',							array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-4">
						{{ Form::text('carton_approved_by'.$generation->id, @$generation->approval->approver->user->username,array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('carton_approved_date'.$generation->id, 'Date:',											array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-2">
						{{ Form::text('carton_approved_date'.$generation->id, @$generation->approval->date,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('carton_approved_#'.$generation->id, 	'Used#:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-1">
						{{ Form::text('carton_approved_#'.$generation->id, 	@$generation->used,								array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
				</div>
			@endforeach
			
			<div class="form-group">
				{{ Form::label('carton_destroyed_by', 		'Undestroyed Labels Destroyed By:',				array('class' => 'col-sm-3 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-3">					
					{{ Form::text('carton_destroyed_by', 	@$batch->batchCartonLabel->batchDestruction->destroyer->user->username, 	array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('carton_destroyed_date', 	'Date:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('carton_destroyed_date', 	@$batch->batchCartonLabel->batchDestruction->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('carton_destroyed_#', 		'Destroyed#:',									array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-1">
					{{ Form::text('carton_destroyed_#', 	@$batch->batchCartonLabel->batchDestruction->amount,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
			
			<hr>
			
			<div class="form-group">
				{{ Form::label('', 							'Heat Seal:', 				array('class' => 'col-sm-2 control-label form-inline text-danger')) }}
				{{ Form::label('target_burst_pressure', 	'Target Burst Pressure:',	array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-1">
					{{ Form::text('target_burst_pressure', 	@$product->productHeatSeal->target,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('alert_limit', 				'Alert Limit:',				array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-1">
					{{ Form::text('alert_limit', 			@$product->productHeatSeal->alert,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('action_limit', 				'Action Limit:',			array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-1">
					{{ Form::text('action_limit', 			@$product->productHeatSeal->action,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>				
			</div>
			
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>time</th>
						<th>Sample #</th>
						<th>Burst Pressure</th>
						<th>Burst Location</th>
						<th>Seal Transfer %</th>
						<th>Wicking(present/absent)</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1; $burstEntries = @$batch->burstEntries or $burstEntries = array();?>					
					@foreach($burstEntries as $batchBurstEntry )
						<tr>
							<td>
								{{ Form::text('burst_time'.$batchBurstEntry->id, 		$batchBurstEntry->time,		array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
							<td>
								{{ Form::text('burst_sample_#'.$batchBurstEntry->id, 	$i,							array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
							<td>
								{{ Form::text('burst_pressure'.$batchBurstEntry->id, 	$batchBurstEntry->pressure,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
							<td>
								{{ Form::text('burst_location'.$batchBurstEntry->id, 	$batchBurstEntry->location,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
							<td>
								{{ Form::text('burst_seal_transfer'.$batchBurstEntry->id, 'N/A',					array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
							<td>
								{{ Form::text('burst_wicking'.$batchBurstEntry->id, 	'N/A',						array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
						</tr>
						<?php $i++; ?>
					@endforeach
				</tbody>
			</table>
			
			<div id="machine_used" class="text-primary text-center">
				<h4>Machine Used</h4>
			</div>
			
			<div class="form-group">
				{{ Form::label('machine_'.@$batch->machineReadings[1]->machine->name, @$batch->machineReadings[1]->machine->name.':',	array('class' => 'col-sm-2 col-sm-offset-2 control-label form-inline')) }}
					
				@foreach($batch->machineReadings as $machineReading)
					{{ Form::label('machine_'.$machineReading->name, $machineReading->type->type.':', array('class' => 'col-sm-1  control-label form-inline')) }}
					<div class="col-sm-1">
						{{ Form::text('high_temp', $machineReading->value,		array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
				@endforeach
					
			</div>
						
			<hr>
			
			<div class="form-group">
				@foreach($batch->sealers as $sealer)
					{{ Form::label('sealed_by0', 'Sealed By:',	array('class' => 'col-sm-2 col-sm-offset-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-3">
						{{ Form::text('sealed_by0', $sealer->user->username,			array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('sealed_by_date0', 'Date:',	array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-2">
						{{ Form::text('sealed_by_date0', $sealer->pivot->date,	array('class' => 'form-control form-inline', 'readonly' => '')) }}					
					</div>
				@endforeach
			</div>						
			
			<hr>

			<div id="inspection" class="text-primary text-center">
				<h4>FINAL QUALITY INSPECTION</h4>
			</div>
			
			<div class="form-group">
				{{ Form::label('target_burst_pressure', 'Sample Size Code Letter:',	array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('target_burst_pressure', 	@$batch->batchInspection->code_letter,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('alert_limit', 'Sample Size:',						array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('alert_limit', 	@$batch->batchInspection->size,								array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('action_limit', '1% AQL Reject Level:',				array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('action_limit', 	@$batch->batchInspection->aql_min.'-'.@$batch->batchInspection->aql_max,								array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
			
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Characteristic</th>
						<th># Rejected</th>
						<th>Pass/Fail</th>
						<th>Burst Inspected By(signature)</th>
						<th>Date</th>
					</tr>
				</thead>
				<tbody id="dynamic_burst">
					<tr>
						<td>
							{{ Form::text('inspection_characteristic_heatSeal', 'Heat Seal',		array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_rejected_heatSeal', 	@$batch->batchInspection->heatSealInspection->rejected,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_pass_heatSeal', 		@$batch->batchInspection->heatSealInspection->pass,							array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_approval_heatSeal', 	@$batch->batchInspection->heatSealInspection->approval->approver->user->username,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_date_heatSeal', 		@$batch->batchInspection->heatSealInspection->approval->date,							array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
					</tr>
					<tr>
						<td>
							{{ Form::text('inspection_characteristic_contents', 'Contents',			array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_rejected_contents', 	@$batch->batchInspection->contentsInspection->rejected,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_pass_contents', 		@$batch->batchInspection->contentsInspection->pass,							array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_approval_contents', 	@$batch->batchInspection->contentsInspection->approval->approver->user->username,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_date_contents', 		@$batch->batchInspection->contentsInspection->approval->date,							array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
					</tr>
					<tr>
						<td>
							{{ Form::text('inspection_characteristic_particulate', 'Particulate',	array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_rejected_particulate', 	@$batch->batchInspection->particulateInspection->rejected,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_pass_particulate', 		@$batch->batchInspection->particulateInspection->pass,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_approval_particulate', 	@$batch->batchInspection->particulateInspection->approval->approver->user->username,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_date_particulate', 		@$batch->batchInspection->particulateInspection->approval->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
					</tr>
					<tr>
						<td>
							{{ Form::text('inspection_characteristic_burstStrength', 'Burst Strength',array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_rejected_burstStrength', 		@$batch->batchInspection->burstStrengthInspection->rejected,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_pass_burstStrength', 			@$batch->batchInspection->burstStrengthInspection->pass,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_approval_burstStrength', 		@$batch->batchInspection->burstStrengthInspection->approval->approver->user->username,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
						<td>
							{{ Form::text('inspection_date_burstStrength', 			@$batch->batchInspection->burstStrengthInspection->approval->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</td>
					</tr>					
				</tbody>
			</table>
			
			<hr>

			<div id="comments" class="text-primary text-center">
				<h4>Comments</h4>
			</div>
						
			<div>
				<?php $comments_text = ""; ?>
				<?php $comments = @$batch->commentBlock->comments or $comments = array();?>	
				@foreach($comments as $comment)
					<?php $comments_text = $comments_text.$comment->text.'\n'; ?>
				@endforeach
				{{ Form::textarea('comments', $comments_text, array('class' => 'form-control form-inline', 'readonly' => '')) }}
			</div>
			
			<hr>
			
			<div id="sterilization" class="text-primary text-center">
				<h4>STERILIZATION INFORMATION / LOT DISPOSITION</h4>
			</div>
			
			<div class="form-group">
				{{ Form::label('sterlize_date', 				'Date Sterlized:',									array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('sterlize_date', 				@$batch->sterilization->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('sterlize_sterlizer', 			'Sterlizer:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('sterlize_sterlizer', 		@$batch->sterilization->sterilizer->user->username,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('sterlize_workOrderNumber', 		'Work Order Number:',								array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('sterlize_workOrderNumber', 	@$batch->sterilization->work_order,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('sterlize_quantity', 			'Quantity:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-1">
					{{ Form::text('sterlize_quantity', 			@$batch->sterilization->quantity,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
			
			<div class="form-group">
				{{ Form::label('release_employee', 			'Released For Distrubtion:',					array('class' => 'col-sm-3 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-3">
					{{ Form::text('release_employee',	 	@$batch->approval->approver->user->username,		array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('release_employeeTitle', 	'Title:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('release_employeeTitle', 	@$batch->approval->approver->titles[0]->name,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('release_date', 				'Date:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('release_date', 			@$batch->approval->date,							array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
			
			<br>

			<div class="form-actions">
				{{-- Form::submit('Submit Batch History Record', array('class' => 'btn btn-success btn-submit col-sm-offset-8')) --}}
			</div>
			{{ Form::close (); }}
	</div>
@stop