@extends ('layouts.masterLayout')

@section ('pagetitle')
	Epimed - Batch History Form
@stop

@section ('content')
	<div class="bg-grey-warm text-primary">
		<div id="form_title" class="text-center">
			<h4>FINAL PRODUCT BATCH HISTORY RECORD</h4>
		</div>
	
		<div id="form_subtitle" class="text-center">
			<h6>IHR-013</h4>
		</div>
	</div>
	<hr>
	<div>

		{{ Form::open (array('url' => '', 'method' => 'put', 'class' => 'form-horizontal', 'role' => 'form')) }}	
		
			<div class="form-group">
				{{ Form::label('final_product', 'Final Product', 	array('class' => 'col-sm-2 control-label form-inline text-primary')) }}
				<div class="col-sm-4">
					{{ Form::text('', 	$product->name,				array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('final_lot_#', 'Final Lot #:', 		array('class' => 'col-sm-2 control-label col-sm-offset-1 form-inline text-primary')) }}
				<div class="col-sm-2">
					{{ Form::text('', 	$batch->lot,				array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>				
			</div>
			
			<div class="form-group">
				{{ Form::label('catalog_#', 'Catalog #', 			array('class' => 'col-sm-2 control-label form-inline text-primary')) }}
				<div class="col-sm-4">
					{{ Form::text('', 	$product->alphanumeric,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('final_quantity', 'Final Quantity',	array('class' => 'col-sm-2 control-label col-sm-offset-1 form-inline text-primary')) }}
				<div class="col-sm-2">
					{{ Form::text('', 	@$batch->sterilization->quantity ,			array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
						
			{{ Form::close (); }}
			
			<hr>
						
			<div id="pouch_label" class="text-primary text-center">
				<h4>Pouch Label</h4>
			</div>
			<?php $batchGenerations = @$batch->batchPouchLabel->batchGenerations or $batchGenerations = array();?>
			@foreach($batchGenerations as $generation )
				{{ Form::open (array('url' => '', 'method' => 'put', 'class' => 'form-horizontal', 'role' => 'form')) }}
					<div class="form-group">
						{{ Form::label('pouch_generated_by'.$generation->id, 	'Generated By:',						array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-4">
							{{ Form::text('', 	$generation->generator->user->username,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
						{{ Form::label('pouch_generated_date'.$generation->id, 	'Date:',								array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-2">
							{{ Form::text('',	$generation->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
						{{ Form::label('pouch_generated_#'.$generation->id, 	'Generated#:',							array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-1">
							{{ Form::text('', 	$generation->amount,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
					</div>
				{{ Form::close (); }}
				{{ Form::open (array('url' => '/forms/batch-history/'.$batch->id.'/update/approve', 'method' => 'put', 'class' => 'form-horizontal', 'role' => 'form')) }}	
				@if(is_null($generation->approval_id))
				
					{{ Form::hidden('batchGeneration', $generation->id, array('readonly' => '')) }}
					{{ Form::hidden('batchPouchLabel', $generation->pouchLabel[0]->getKey(), array('readonly' => '')) }}
					<div class="form-group">
						{{ Form::label('approved_by', 			'Approved For Use By:',							array('class' => 'col-sm-2 control-label form-inline' )) }}
						<div class="col-sm-4">
							{{ Form::text('approved_by', 		Auth::user()->username,	array('class' => 'form-control form-inline')) }}
						</div>
						{{ Form::label('approved_date', 		'Date:',										array('class' => 'col-sm-1 control-label form-inline')) }}
						<div class="col-sm-2">
							{{ Form::text('approved_date', 	date('Y-m-d H:i:s'),					array('class' => 'form-control form-inline')) }}
						</div>
						{{ Form::label('approved_#', 			'Used#:',										array('class' => 'col-sm-1 control-label form-inline')) }}
						<div class="col-sm-1">
							{{ Form::text('approved_#', 		'',								array('class' => 'form-control form-inline')) }}
						</div>
					</div>
					
					<div class="form-actions">
					{{ Form::submit('Submit Approval for this item', array('class' => 'btn btn-success btn-submit col-sm-offset-8')) }}
					</div>			
				@else
					<div class="form-group">
						{{ Form::label('pouch_approved'.$generation->id, 			'Approved For Use By:',							array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-4">
							{{ Form::text('pouch_approved_by'.$generation->id, 		@$generation->approval->approver->user->username,array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
						{{ Form::label('pouch_approved_date'.$generation->id, 		'Date:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-2">
							{{ Form::text('pouch_approved_date'.$generation->id, 	@$generation->approval->date,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
						{{ Form::label('pouch_approved_#'.$generation->id, 			'Used#:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-1">
							{{ Form::text('pouch_approved_#'.$generation->id, 		@$generation->used,								array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
					</div>
				@endif
				{{ Form::close (); }}
			@endforeach
					
			<hr>
			
			<div id="carton_label" class="text-primary text-center">
				<h4>Carton Label</h4>
			</div>
			<?php $batchGenerations = @$batch->batchCartonLabel->batchGenerations or $batchGenerations = array();?>
			@foreach($batchGenerations as $generation )
				{{ Form::open (array('url' => '', 'method' => 'put', 'class' => 'form-horizontal', 'role' => 'form')) }}
					<div class="form-group">
						{{ Form::label('carton_generated_by'.$generation->id, 		'Generated By:',						array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-4">
							{{ Form::text('', 	$generation->generator->user->username,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
						{{ Form::label('carton_generated_date'.$generation->id, 	'Date:',								array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-2">
							{{ Form::text('', 	$generation->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
						{{ Form::label('carton_generated_#'.$generation->id, 		'Generated#:',							array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-1">
							{{ Form::text('', 	$generation->amount,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
					</div>
				{{ Form::close (); }}				
				{{ Form::open (array('url' => '/forms/batch-history/'.$batch->id.'/update/approve', 'method' => 'put', 'class' => 'form-horizontal', 'role' => 'form')) }}	
				@if(is_null($generation->approval_id))
					{{ Form::hidden('generation', $generation->id, array('readonly' => '')) }}
					{{ Form::hidden('batchCartonLabel', $generation->cartonLabel[0]->getKey(), array('readonly' => '')) }}
					<div class="form-group">
						{{ Form::label('approved', 			'Approved For Use By:',							array('class' => 'col-sm-2 control-label form-inline' )) }}
						<div class="col-sm-4">
							{{ Form::text('approved_by', 	Auth::user()->username,	array('class' => 'form-control form-inline')) }}
						</div>
						{{ Form::label('approved_date', 		'Date:',										array('class' => 'col-sm-1 control-label form-inline')) }}
						<div class="col-sm-2">
							{{ Form::text('approved_date', 	date('Y-m-d H:i:s'),					array('class' => 'form-control form-inline')) }}
						</div>
						{{ Form::label('approved_#', 			'Used#:',										array('class' => 'col-sm-1 control-label form-inline')) }}
						<div class="col-sm-1">
							{{ Form::text('approved_#', 		'',								array('class' => 'form-control form-inline')) }}
						</div>
					</div>
					<div class="form-actions">
						{{ Form::submit('Submit Approval for this item', array('class' => 'btn btn-success btn-submit col-sm-offset-8')) }}
					</div>
				@else
					<div class="form-group">
						{{ Form::label('carton_approved'.$generation->id, 			'Approved For Use By:',							array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-4">
							{{ Form::text('carton_approved_by'.$generation->id, 		@$generation->approval->approver->user->username,array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
						{{ Form::label('carton_approved_date'.$generation->id, 		'Date:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-2">
							{{ Form::text('carton_approved_date'.$generation->id, 	@$generation->approval->date,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
						{{ Form::label('carton_approved_#'.$generation->id, 			'Used#:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
						<div class="col-sm-1">
							{{ Form::text('carton_approved_#'.$generation->id, 		@$generation->used,								array('class' => 'form-control form-inline', 'readonly' => '')) }}
						</div>
					</div>
				@endif
				{{ Form::close (); }}
			@endforeach		
	</div> 
@stop