@extends ('layouts.masterLayout')

@section ('pagetitle')
	Epimed - Batch History Form
@stop

@section ('content')
	<div class="bg-grey-warm text-primary">		
		<div id="form_title" class="text-center">
			<h4>FINAL PRODUCT BATCH HISTORY RECORD</h4>
		</div>		
	
		<div id="form_subtitle" class="text-center">
			<h6>IHR-013</h4>
		</div>		
	</div>
	<hr>
	<div>	
		{{ Form::open (array ('url' => '', 'method' => 'post', 'class' => 'form-horizontal', 'role' => 'form')) }}	
			<div class="form-group">
				{{ Form::label('final_product', 'Final Product', 	array('class' => 'col-sm-2 control-label form-inline text-primary')) }}
				<div class="col-sm-4">
					{{ Form::text('final_product', 	$product->name,				array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('final_lot_#', 'Final Lot #:', 		array('class' => 'col-sm-2 control-label col-sm-offset-1 form-inline text-primary')) }}
				<div class="col-sm-2">
					{{ Form::text('final_lot_#', 	$batch->lot,				array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>				
			</div>
			
			<div class="form-group">
				{{ Form::label('catalog_#', 'Catalog #', 			array('class' => 'col-sm-2 control-label form-inline text-primary')) }}
				<div class="col-sm-4">
					{{ Form::text('catalog_#', 	$product->alphanumeric,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('final_quantity', 'Final Quantity',	array('class' => 'col-sm-2 control-label col-sm-offset-1 form-inline text-primary')) }}
				<div class="col-sm-2">
					{{ Form::text('final_quantity', 	@$batch->sterilization->quantity ,			array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
			{{-- "Todo add button to show BoM here" --}}
			<div class="form-group">
				{{ Form::label('component_product_#0', 'Componenet Product #',	array('class' => 'col-sm-3 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-3">
					{{ Form::text('component_product_#0', 	'',					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('lot_#0', 'Lot #:',								array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2 col-sm-offset-1">
					{{ Form::text('lot_#0', 	'',								array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
			
			<div class="form-group">
				{{ Form::label('component_product_#1', 'Componenet Product #',	array('class' => 'col-sm-3 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-3">
					{{ Form::text('component_product_#1', 	'',					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('lot_#1', 'Lot #:',								array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2 col-sm-offset-1">
					{{ Form::text('lot_#1', 	'',								array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
			
			<hr>
						
			<div id="pouch_label" class="text-primary text-center">
				<h4>Pouch Label</h4>
			</div>
			<?php $batchGenerations = @$batch->batchPouchLabel->batchGenerations or $batchGenerations = array();?>
			@foreach($batchGenerations as $generation )
				<div class="form-group">
					{{ Form::label('pouch_generated_by'.$generation->id, 	'Generated By:',						array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-4">
						{{ Form::text('pouch_generated_by'.$generation->id, $generation->generator->user->username,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('pouch_generated_date'.$generation->id, 	'Date:',								array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-2">
						{{ Form::text('pouch_generated_date'.$generation->id,$generation->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('pouch_generated_#'.$generation->id, 	'Generated#:',							array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-1">
						{{ Form::text('pouch_generated_#'.$generation->id, 	$generation->amount,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
				</div>
			
				<div class="form-group">
					{{ Form::label('pouch_approved'.$generation->id, 			'Approved For Use By:',							array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-4">
						{{ Form::text('pouch_approved_by'.$generation->id, 		@$generation->approval->approver->user->username,array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('pouch_approved_date'.$generation->id, 		'Date:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-2">
						{{ Form::text('pouch_approved_date'.$generation->id, 	@$generation->approval->date,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('pouch_approved_#'.$generation->id, 			'Used#:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-1">
						{{ Form::text('pouch_approved_#'.$generation->id, 		@$generation->used,								array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
				</div>
			@endforeach

			<div class="form-group">
				{{ Form::label('pouch_destroyed_by', 	'Undestroyed Labels Destroyed By:',				array('class' => 'col-sm-3 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-3">
					{{ Form::text('pouch_destroyed_by', @$batch->batchPouchLabel->batchDestruction->destroyer->user->username,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('pouch_destroyed_date', 	'Date:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('pouch_destroyed_date', @$batch->batchPouchLabel->batchDestruction->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('pouch_destroyed_#', 	'Destroyed#:',									array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-1">
					{{ Form::text('pouch_destroyed_#', 	@$batch->batchPouchLabel->batchDestruction->amount,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
						
			<hr>
			
			<div id="carton_label" class="text-primary text-center">
				<h4>Carton Label</h4>
			</div>
			<?php $batchGenerations = @$batch->batchCartonLabel->batchGenerations or $batchGenerations = array();?>
			@foreach($batchGenerations as $generation )
				<div class="form-group">
					{{ Form::label('carton_generated_by'.$generation->id, 		'Generated By:',						array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-4">
						{{ Form::text('carton_generated_by'.$generation->id, 	$generation->generator->user->username,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('carton_generated_date'.$generation->id, 	'Date:',								array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-2">
						{{ Form::text('carton_generated_date'.$generation->id, 	$generation->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('carton_generated_#'.$generation->id, 		'Generated#:',							array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-1">
						{{ Form::text('carton_generated_#'.$generation->id, 	$generation->amount,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
				</div>

				<div class="form-group">
					{{ Form::label('carton_approved_by'.$generation->id, 	'Approved For Use By:',							array('class' => 'col-sm-2 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-4">
						{{ Form::text('carton_approved_by'.$generation->id, @$generation->approval->approver->user->username,array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('carton_approved_date'.$generation->id, 'Date:',											array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-2">
						{{ Form::text('carton_approved_date'.$generation->id, @$generation->approval->date,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
					{{ Form::label('carton_approved_#'.$generation->id, 	'Used#:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
					<div class="col-sm-1">
						{{ Form::text('carton_approved_#'.$generation->id, 	@$generation->used,								array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
				</div>
			@endforeach
			
			<div class="form-group">
				{{ Form::label('carton_destroyed_by', 		'Undestroyed Labels Destroyed By:',				array('class' => 'col-sm-3 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-3">					
					{{ Form::text('carton_destroyed_by', 	@$batch->batchCartonLabel->batchDestruction->destroyer->user->username, 	array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('carton_destroyed_date', 	'Date:',										array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-2">
					{{ Form::text('carton_destroyed_date', 	@$batch->batchCartonLabel->batchDestruction->date,						array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('carton_destroyed_#', 		'Destroyed#:',									array('class' => 'col-sm-1 control-label form-inline', 'readonly' => '')) }}
				<div class="col-sm-1">
					{{ Form::text('carton_destroyed_#', 	@$batch->batchCartonLabel->batchDestruction->amount,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
			
			<hr>
			
			{{ Form::open (array('url' => '', 'method' => 'POST', 'class' => 'form-horizontal', 'role' => 'form')) }}	
			<div class="form-group">
				{{ Form::label('', 'Heat Seal:', array('class' => 'col-sm-2 control-label form-inline text-danger')) }}
				{{ Form::label('target_burst_pressure', 'Target Burst Pressure:',	array('class' => 'col-sm-2 control-label form-inline')) }}
				<div class="col-sm-1">
					{{ Form::text('target_burst_pressure', 	'',						array('class' => 'form-control form-inline')) }}
				</div>
				{{ Form::label('alert_limit', 'Alert Limit:',						array('class' => 'col-sm-2 control-label form-inline')) }}
				<div class="col-sm-1">
					{{ Form::text('alert_limit', 	'',								array('class' => 'form-control form-inline')) }}
				</div>
				{{ Form::label('action_limit', 'Action Limit:',						array('class' => 'col-sm-2 control-label form-inline')) }}
				<div class="col-sm-1">
					{{ Form::text('action_limit', 	'',								array('class' => 'form-control form-inline')) }}
				</div>
			</div>
			
			@if(!$batch->burstEntries->isEmpty())
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>time</th>
						<th>Sample #</th>
						<th>Burst Pressure</th>
						<th>Burst Location</th>
						<th>Seal Transfer %</th>
						<th>Wicking(present/absent)</th>
					</tr>
				</thead>
				<tbody>
					<?php $i=1; $burstEntries = @$batch->burstEntries or $burstEntries = array();?>					
					@foreach($burstEntries as $batchBurstEntry )
						<tr>
							<td>
								{{ Form::text('burst_time'.$batchBurstEntry->id, 		$batchBurstEntry->time,		array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
							<td>
								{{ Form::text('burst_sample_#'.$batchBurstEntry->id, 	$i,							array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
							<td>
								{{ Form::text('burst_pressure'.$batchBurstEntry->id, 	$batchBurstEntry->pressure,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
							<td>
								{{ Form::text('burst_location'.$batchBurstEntry->id, 	$batchBurstEntry->location,	array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
							<td>
								{{ Form::text('burst_seal_transfer'.$batchBurstEntry->id, 'N/A',					array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
							<td>
								{{ Form::text('burst_wicking'.$batchBurstEntry->id, 	'N/A',						array('class' => 'form-control form-inline', 'readonly' => '')) }}
							</td>
						</tr>
						<?php $i++; ?>
					@endforeach
				</tbody>
			</table>
			@else
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>time</th>
						<th>Sample #</th>
						<th>Burst Pressure</th>
						<th>Burst Location</th>
						<th>Seal Transfer %</th>
						<th>Wicking(present/absent)</th>
					</tr>
				</thead>
				<tbody id="dynamic_burst">
					<tr data-number="0">
						<td>
							<input class="form-control form-inline" name="burst_time" data-name="burst_time" rows="1" form="batch_burst" type="text" value="">
						</td>
						<td>
							<input class="form-control form-inline" name="burst_sample_#'0'" type="text" readonly="" value="1">
						</td>
						<td>
							<input class="form-control form-inline" name="burst_pressure" data-name="burst_pressure" rows="1" form="batch_burst" type="text" value="">
						</td>
						<td>
							<input class="form-control form-inline" name="burst_location" data-name="burst_location" rows="1" form="batch_burst" type="text" value="">
						</td>
						<td>
							<input class="form-control form-inline" name="burst_seal_transfer" data-name="burst_seal_transfer" rows="1" form="batch_burst" type="text" value="">
						</td>
						<td>
							<input class="form-control form-inline" name="burst_wicking" data-name="burst_wicking" rows="1" form="batch_burst" type="text" value="">
						</td>
					</tr>
					
				</tbody>
			</table>
				
			<div class="form-group">
				<div class="col-sm-1 col-sm-offset-10 col-xs-offset-8">
					<a title="click to add another row" id="add_burst_row_btn" class="add_row_btn btn btn-warning" data-counter="1" data-name="burst">
						<i class="fa fa-plus-circle"></i>
					</a>
				</div>
			</div>
			{{ HTML::decode (
					Form::button (
						'<i class="fa fa-cloud-upload"></i> Add Bursts to Batch',
						array (
							'id' => 'create_burst_batch',
							'class' => 'btn btn-success btn-submit col-sm-offset-8',
							'type' => 'button',
							'data-batch' => $batch->id,
							'data-type' => 'POST'
						)
					)
				) }}
			@endif
			{{ Form::close (); }}
			{{ Form::open (array ('url' => '', 'method' => 'post', 'class' => 'form-horizontal', 'role' => 'form')) }}	
			<div id="machine_used" class="text-primary text-center">
				<h4>Machine Used</h4>
			</div>
			
			<div class="form-group">
				{{ Form::label('machine_'.@$batch->machineReadings[1]->machine->name, @$batch->machineReadings[1]->machine->name.':',	array('class' => 'col-sm-2 col-sm-offset-2 control-label form-inline')) }}
					
				@foreach($batch->machineReadings as $machineReading)
					{{ Form::label('machine_'.$machineReading->name, $machineReading->type->type.':', array('class' => 'col-sm-1  control-label form-inline')) }}
					<div class="col-sm-1">
						{{ Form::text('high_temp', $machineReading->value,		array('class' => 'form-control form-inline', 'readonly' => '')) }}
					</div>
				@endforeach
					
			</div>
						
			<hr>
			
			{{ Form::close (); }}
		
	</div>
	{{ HTML::script('/js/dynamic_batch_history_form_injection.js') }}
 
@stop