@extends ('layouts.masterLayout')

@section ('pagetitle')
	Epimed - Batch History Form
@stop

@section ('content')
	<div class="bg-grey-warm text-primary">
		<div id="form_title" class="text-center">
			<h4>FINAL PRODUCT BATCH HISTORY RECORD</h4>
		</div>
	
		<div id="form_subtitle" class="text-center">
			<h6>IHR-013</h4>
		</div>
	</div>
	<hr>
	<div>

		{{ Form::open (array('url' => '/forms/batch-history/'.$batch->id.'/update/generate', 'method' => 'put', 'class' => 'form-horizontal', 'role' => 'form')) }}
			<div class="form-group">
				{{ Form::label('final_product', 'Final Product', 	array('class' => 'col-sm-2 control-label form-inline text-primary')) }}
				<div class="col-sm-4">
					{{ Form::text('', 	$product->name,				array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('final_lot_#', 'Final Lot #:', 		array('class' => 'col-sm-2 control-label col-sm-offset-1 form-inline text-primary')) }}
				<div class="col-sm-2">
					{{ Form::text('', 	$batch->lot,				array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>				
			</div>
			
			<div class="form-group">
				{{ Form::label('catalog_#', 'Catalog #', 			array('class' => 'col-sm-2 control-label form-inline text-primary')) }}
				<div class="col-sm-4">
					{{ Form::text('', 	$product->alphanumeric,					array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
				{{ Form::label('final_quantity', 'Final Quantity',	array('class' => 'col-sm-2 control-label col-sm-offset-1 form-inline text-primary')) }}
				<div class="col-sm-2">
					{{ Form::text('', 	@$batch->sterilization->quantity ,			array('class' => 'form-control form-inline', 'readonly' => '')) }}
				</div>
			</div>
						
			<hr>

			<div id="pouch_label" class="text-primary text-center">
				<h4>Pouch Label</h4>
			</div>
			
			<div class="form-group">
				{{ Form::label('pouch_generated_by', 'Generated By:',	array('class' => 'col-sm-2 control-label form-inline')) }}
				<div class="col-sm-4">
					{{ Form::text('pouch_generated_by', 	'',			array('class' => 'form-control form-inline')) }}
				</div>
				{{ Form::label('pouch_generated_date', 'Date:',		array('class' => 'col-sm-1 control-label form-inline')) }}
				<div class="col-sm-2">
					{{ Form::text('pouch_generated_date', 	date('Y-m-d H:i:s'),		array('class' => 'form-control form-inline')) }}
				</div>
				{{ Form::label('pouch_generated_#', 'Generated#:',		array('class' => 'col-sm-1 control-label form-inline')) }}
				<div class="col-sm-1">
					{{ Form::text('pouch_generated_#', 	'',			array('class' => 'form-control form-inline')) }}
				</div>
			</div>		
			
			{{--
			<div id="dynamic_pouch">

			</div>
			
			<div class="form-group">
				<div class="col-sm-1 col-sm-offset-10 col-xs-offset-8">
					<a title="click to add another pouch generation" id="add_pouch_generation_btn" class="add_generation_btn btn btn-warning" data-counter="1" data-name="pouch">
						<i class="fa fa-plus-circle"></i>
					</a>
				</div>
			</div>			
			--}}
			<hr>
			
			<div id="carton_label" class="text-primary text-center">
				<h4>Carton Label</h4>
			</div>
			<div class="form-group">
				{{ Form::label('carton_generated_by', 'Generated By:',	array('class' => 'col-sm-2 control-label form-inline')) }}
				<div class="col-sm-4">
					{{ Form::text('carton_generated_by', 	'',			array('class' => 'form-control form-inline')) }}
				</div>
				{{ Form::label('carton_generated_date', 'Date:',	array('class' => 'col-sm-1 control-label form-inline')) }}
				<div class="col-sm-2">
					{{ Form::text('carton_generated_date', 	date('Y-m-d H:i:s'),		array('class' => 'form-control form-inline')) }}
				</div>
				{{ Form::label('carton_generated_#', 'Generated#:',	array('class' => 'col-sm-1 control-label form-inline')) }}
				<div class="col-sm-1">
					{{ Form::text('carton_generated_#', 	'',			array('class' => 'form-control form-inline')) }}
				</div>
			</div>			

			{{--
			<div id="dynamic_carton">

			</div>
			
			<div class="form-group">
				<div class="col-sm-1 col-sm-offset-10 col-xs-offset-8">
					<a title="click to add another carton generation" id="add_carton_generation_btn" class="add_generation_btn btn btn-warning" data-counter="1" data-name="carton">
						<i class="fa fa-plus-circle"></i>
					</a>
				</div>
			</div>			
			--}}
			<br>
			
			<div class="form-actions">
				{{ Form::submit('Submit Batch History Generations', array('class' => 'btn btn-success btn-submit col-sm-offset-8')) }}
			</div>
			

			{{ Form::close (); }}
		
	</div>
 
@stop